spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/OrderService
  logging:
    level:
      org.springframework.web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
